/*
This file was created by 12345koip for the
LuGo Structure Dumper, a subproject of the
LuGo executor.

See LICENSE and README for details.
*/

#pragma once
#include <string>
#include <sstream>


#define COMMON_FILE_TOP "/*\nThis header file was generated by the\nLuGo Structure Dumper, a subproject of the\nLuGo executor, both created by 12345koip.\n*/"
#define INCLUDE_ONCE "#pragma once"
#define LUAU_DUMP_INCLUDES "#include <cstdint>"
#define HEADER_FILE_EXTENTION ".h"
#define NEWLINE "\n"
#define GENERIC_POINTER "void*"
#define TAB_INDENT "   "

//forward declarations.
#define FORWARD_TVALUE "struct TValue;"
#define FORWARD_GLOBAL_STATE "struct global_State;"
#define FORWARD_CALL_INFO "struct CallInfo;"
#define FORWARD_TSTRING "struct TString;"
#define FORWARD_LUA_STATE "struct lua_State;"
#define FORWARD_LUA_TABLE "struct LuaTable;"
#define FORWARD_UPVAL "struct UpVal;"
#define FORWARD_GCOBJECT "union GCObject;"
#define FORWARD_VALUE "union Value;"

//typedefs.
#define STKID_TYPEDEF "typedef TValue* StkId;"
#define REMOVE_STRUCT_PREF "typedef struct TValue TValue;\ntypedef struct global_State global_State;\ntypedef struct UpVal UpVal;\ntypedef struct LuaTable LuaTable;\ntypedef struct CallInfo CallInfo;\ntypedef struct TString TString; typedef struct lua_State lua_State;\ntypedef union GCObject GCObject;\ntypedef union Value Value;"

namespace LuDumper {
    namespace FileBits {
        //returns structures that cannot change, such as unions.
        std::string GetStaticLuauStructs();
    }
}